
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bcl
      POSTGRES_USER: atec
      POSTGRES_PASSWORD: atec
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: